config/routes.rb
Criduino::Application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", :locale => LOCALES do
	resources :arduinos
  
	resources :users
		
	resource :confirmation, :only => [:show]
		
	resource :user_sessions, :only => [:create, :new, :destroy]
  end

  get "arduinos/:id/leitura" => "arduinos#leitura"
  get "arduinos/:id/escrita" => "arduinos#escrita"

  match '/:locale' => 'home#index', :locale => LOCALES
  root :to => "home#index"
end

app/models/arduino.rb
class Arduino < ActiveRecord::Base
  belongs_to :user

  attr_accessible :mac, :name
  
  validates_presence_of :mac, :name
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :arduinos, :dependent => :destroy

  attr_accessible :email, :full_name, :password, :password_confirmation
  
  validates_presence_of :email, :full_name
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_uniqueness_of :email
  
  has_secure_password
  
  before_create :generate_token
  
  scope :confirmed, where('confirmed_at IS NOT NULL')
  
  def generate_token
    self.confirmation_token = SecureRandom.urlsafe_base64
  end
  
  def confirm!
    return if confirmed?
	
	self.confirmed_at = Time.current
	self.confirmation_token = ''
	save!
  end
  
  def confirmed?
   confirmed_at.present?
  end
  
  def self.authenticate(email, password)
    confirmed.
	find_by_email(email).
	try(:authenticate, password)  
  end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Validations
  include ActiveModel::Conversion
  
  extend ActiveModel::Translation
  extend ActiveModel::Naming
  
  attr_accessor :email, :password
  
  validates_presence_of :email, :password
  
  def initialize(session, attributes={})
    @session = session
	@email = attributes[:email]
	@password = attributes[:password]
  end
  
  def authenticate
    user = User.authenticate(@email, @password)
	
	if user.present?
	  store(user)
	else
	  errors.add(:base, :invalid_login)
	  false
	end
  end
  
  def store(user)
    @session[:user_id] = user.id
  end
  
  def persisted?
    false
  end
  
  def destroy
    @session[:user_id] = nil
  end
  
  def current_user
    User.find(@session[:user_id])
  end
  
  def user_signed_in?
    @session[:user_id].present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  delegate :current_user, :user_signed_in? , :to => :user_session
  helper_method :current_user, :user_signed_in?
  
  before_filter :set_locale
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def default_url_options
    { :locale => I18n.locale }
  end
  
  def user_session
    UserSession.new(session)
  end
  
  def require_authentication
    unless user_signed_in?
	  redirect_to new_user_sessions_path, :alert => t('flash.alert.needs_login')
	end
  end
  
  def require_no_authentication
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/arduinos_controller.rb
class ArduinosController < ApplicationController
  helper :all
  before_filter :require_authentication, :only => [:new, :edit, :create, :update, :destroy]


  def index
    @arduinos = Arduino.all
  end

  def show
    arduino_model = Arduino.find(params[:id])
	@arduino = ArduinoPresenter.new(arduino_model, self)
  end

  def new
    @arduino = current_user.arduinos.build
  end

  def edit
    @arduino = current_user.arduinos.find(params[:id])
  end

  def create
    @arduino = current_user.arduinos.build(params[:arduino])

    if @arduino.save
      redirect_to @arduino, :notice => t('flash.notice.arduino_created')
    else
      render action: "new"
    end
  end

  def update
    @arduino = current_user.arduinos.find(params[:id])

    if @arduino.update_attributes(params[:arduino])
      redirect_to @arduino, :notice => t('flash.notice.arduino_updated')
    else
      render :action => "edit"
    end
  end

  def destroy
    @arduino = current_user.arduinos.find(params[:id])
    @arduino.destroy

	redirect_to arduinos_url
  end

  def leitura
    require 'socket'
    require 'openssl'
    @arduino = current_user.arduinos.find(params[:id])
    server = TCPServer.new('192.168.0.103', 3000)
    loop do
      Thread.start(server.accept) do |client|
        chain = client.gets
        maca = @arduino.mac + "\r\n"
        if (chain == maca)
          client.puts(1)
          server.close
        end
      end
      client.close
    end
  end
  
  def escrita
    require 'socket'
    require 'openssl'
    @arduino = current_user.arduinos.find(params[:id])
    server = TCPServer.new('192.168.0.103', 3000)
    loop do
      Thread.start(server.accept) do |client|
        chain = client.gets
        maca = @arduino.mac + "\r\n"
        if (chain == maca)
          client.puts(0)
          server.close
        end
      end
      client.close
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by_confirmation_token(params[:token])
	
	if user.present?
	  user.confirm!
	  redirect_to user, :notice => I18n.t('users.confirmations.success')
	else
	  redirect_to root_path
	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_authentication, :only => [:new, :create]
  before_filter :require_authentication, :only => :destroy

  def new
    @session = UserSession.new(session)
  end
  
  def create
    @session = UserSession.new(session, params[:user_session])
	if @session.authenticate
	  redirect_to user_path(current_user), :notice => t('flash.notice.signed_in')
	else
	  render :new
	end
  end
  
  def destroy
    user_session.destroy
	redirect_to root_path, :notice => t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_authentication, :only => [:new, :create]
  before_filter :can_change, :only => [:edit, :update]

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
	if @user.save
	  SignupMailer.confirm_email(@user).deliver
	  redirect_to @user, :notice => I18n.t('users.new.success')
	else
	  render :new
	end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
	if @user.update_attributes(params[:user])
	  redirect_to @user, :notice => I18n.t('users.edit.success')
	else
	  render :edit
	end
  end
  
  private
	
  def can_change
	  unless user_signed_in? && current_user == user
		redirect_to user_path(params[:id])
	  end
  end
	
  def user
	@user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
	  content_tag :div, model.errors[attribute].first, :class => 'error_message'
	end
  end
end

app/helpers/arduinos_helper.rb
module ArduinosHelper
	def belongs_to_user(arduino)
		user_signed_in? && arduino.user == current_user
	end
end

app/views/arduinos/_arduino.html.erb
<article class="arduino">
  <% if belongs_to_user(arduino) %>
      <h2><%= link_to arduino.name, arduino.route %></h2>
    <span class="created">
      <%= t '.owner_html', :owner => arduino.user.full_name %>
    </span>
      <p>
	  <span class="mac address">
	    <%= t '.mac', :mac => arduino.mac %>
	  </span>
      </p>
      <p>
        <%= link_to "Ativar", :action => "leitura", :controller => "arduinos", remote: true %>
        <%= link_to "Desativar", :action => "escrita", :controller => "arduinos", remote: true %>
      </p>
      <ul>
        <li><%= link_to t('.edit'), edit_arduino_path(arduino.route) %></li>
        <li><%= link_to t('.destroy'), arduino_path(arduino.route), :method => :delete, :data => {:confirm => t('dialogs.destroy')} %></li>
      </ul>
  <% end %>
</article>

app/views/arduinos/_form.html.erb
<% if @arduino.errors.any? %>
	<div id="error_explanation">
		<%= t 'general.form_error' %>
	</div>
<% end %>

<%= form_for @arduino do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= error_tag @arduino, :name %>
	</p>
	<p>
		<%= f.label :mac %>
		<%= f.text_field :mac %>
		<%= error_tag @arduino, :mac %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/arduinos/edit.html.erb
<h1><%= t 'arduino.edit.name' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), arduinos_path %>

app/views/arduinos/index.html - Copia.erb
<h1><%= t '.name' %></h1>
 
<table>
  <tr>
    <th><%= t '.ardname' %></th>
    <th><%= t '.mac' %></th>
  </tr>
 
  <% @arduinos.each do |arduino| %>
    <% if belongs_to_user(arduino) %>
      <tr>
        <td><%= arduino.name %></td>
        <td><%= arduino.mac %></td>
      </tr>
	<% end %>
  <% end %>
</table>

app/views/arduinos/index.html.erb
<h1><%= t '.name' %></h1>
 
<table>
  <tr>
    <th><%= t '.ardname' %></th>
    <th><%= t '.mac' %></th>
  </tr>
 
  <% @arduinos.each do |arduino| %>
    <% if belongs_to_user(arduino) %>
      <tr>
        <td><%= link_to arduino.name, arduino %></td>
        <td><%= arduino.mac %></td>
      </tr>
	<% end %>
  <% end %>
</table>

app/views/arduinos/new.html.erb
<h1><%= t 'arduinos.new.name' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), arduinos_path %>

app/views/arduinos/show.html.erb
<%= render @arduino %>

app/views/home/index.html.erb
<h1>CRIduino</h1>
  <p>
    Escolha uma das ações a seguir:
	<ul>
	  <li><%= link_to t('layout.signup'), new_user_path %></l1>
	  <li><%= link_to t('layout.login'), new_user_sessions_path %></li>
	</ul>
  </p>

app/views/layouts/_user_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.new_arduino'), new_arduino_path %></li>
		<li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
		<li><%= link_to t('layout.signout'), user_sessions_path, :method => :delete %></li>
	</ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.signup'), new_user_path %></li>
		<li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRIduino</title>
  <link href='http://fonts.googleapis.com/css?family='Helvetica' rel='stylesheet' type='text/css' >
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div id="header_wrap">
			<h1><%= link_to "CRIduino", root_path %></h1>
			<% if user_signed_in? %>
				<%= render 'layouts/user_navbar' %>
			<% else %>
				<%= render 'layouts/visitor_navbar' %>
			<% end %>
		</div>
	</header>

  <div id="content">
    <% if notice.present? %>
	  <p id="notice"><%= notice %></p>
	<% end %>
	<% if alert.present? %>
	  <p id="alert"><%= alert %></p>
	<% end %>
	
	<%= yield %>
  </div>
</body>
</html>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @session.errors.has_key? :base %>
  <div id="error_explanation">
    <%= @session.errors[:base].join(', ') %>
  </div>
<% end %>

<%= form_for @session do |f| %>
  <p>
    <%= f.label :email %>
	<%= f.text_field :email %>
	<%= error_tag @session, :email %>
  </p>
  <p>
    <%= f.label :password %>
	<%= f.password_field :password %>
	<%= error_tag @session, :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %></p>

app/views/users/_form.html.erb
<%if @user.errors.any? %>
  <div id="error_explanation">
    <%= t 'general.form_error' %>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :full_name %><br />
	<%= f.text_field :full_name %>
	<%= error_tag @user, :full_name %>
  </p>
  <p>
    <%= f.label :email %><br />
	<%= f.text_field :email %>
	<%= error_tag @user, :email %>
  </p>
  <p>
    <%= f.label :password %><br />
	<%= f.password_field :password %>
	<%= error_tag @user, :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %>
	<%= error_tag @user, :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h1><%= t '.title', :user_name => @user.full_name %></h1>

<%= link_to t('.arduinos'), arduinos_path %>
<%= link_to t('.edit'), edit_user_path(@user) %>